#!/bin/bash

# Deploy Web UI Script - Bash Version
# This script builds and deploys the React web UI to S3 with CloudFront
# Includes automatic API endpoint configuration from ALB stack

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Load environment configuration from project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../.env.dev" ]; then
    source "$SCRIPT_DIR/../.env.dev"
fi

BUCKET_NAME="${1:-${UI_BUCKET:-${BUCKET_PREFIX:+${BUCKET_PREFIX}-}rfp-ui-${ENVIRONMENT:-dev}}}"
REGION="${2:-${REGION:-us-east-1}}"
ENVIRONMENT="${ENVIRONMENT:-dev}"

# Guard: bucket name must not be empty
if [ -z "$BUCKET_NAME" ]; then
    echo -e "${RED}❌ Bucket name is empty. Provide bucket arg or set UI_BUCKET or BUCKET_PREFIX/ENVIRONMENT variables.${NC}"
    echo "Usage: ./deploy.sh <bucket-name> [region]"
    exit 1
fi

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║          WEB UI DEPLOYMENT SCRIPT                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Environment:${NC} $ENVIRONMENT"
echo -e "${BLUE}Region:${NC} $REGION"
echo -e "${BLUE}Bucket:${NC} $BUCKET_NAME"
echo ""

# Check if bucket exists (should be created by CloudFormation with CloudFront)
echo -e "${YELLOW}[1/6] Checking S3 bucket...${NC}"
if aws s3 ls "s3://$BUCKET_NAME" --region $REGION >/dev/null 2>&1; then
    echo -e "${GREEN}  ✅ Bucket exists: $BUCKET_NAME${NC}"
else
    echo -e "${RED}  ❌ Bucket not found: $BUCKET_NAME${NC}"
    echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
    echo "     1. Check if CloudFormation stack created the bucket:"
    echo "        aws cloudformation describe-stack-resources --stack-name rfp-${ENVIRONMENT}-cloudfront --region $REGION"
    echo "     2. Deploy infrastructure first:"
    echo "        cd ../rfp-infrastructure && ./scripts/deploy-cloudfront-manual.sh"
    echo "     3. Verify bucket name matches CloudFormation output"
    exit 1
fi

# Get API endpoint from ALB stack
echo ""
echo -e "${YELLOW}[2/6] Configuring API endpoint...${NC}"
ALB_STACK_NAME="rfp-${ENVIRONMENT}-java-api-alb"
ALB_URL=$(aws cloudformation describe-stacks \
    --stack-name "$ALB_STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`LoadBalancerUrl`].OutputValue' \
    --output text 2>/dev/null || echo "")

if [ -n "$ALB_URL" ] && [ "$ALB_URL" != "None" ]; then
    echo -e "${GREEN}  ✅ Found ALB endpoint: $ALB_URL${NC}"
    
    # Create/update .env.production with ALB endpoint
    cat > "$SCRIPT_DIR/.env.production" <<EOF
# Production environment configuration
# Auto-generated by deploy.sh from CloudFormation ALB stack outputs
VITE_API_BASE_URL=${ALB_URL}/api
VITE_APP_ENV=production
VITE_DEBUG=false
EOF
    echo -e "${GREEN}  ✅ Updated .env.production with ALB endpoint${NC}"
else
    echo -e "${YELLOW}  ⚠️  ALB stack not found, checking for existing .env.production...${NC}"
    if [ -f "$SCRIPT_DIR/.env.production" ]; then
        echo -e "${GREEN}  ✅ Using existing .env.production${NC}"
    else
        echo -e "${RED}  ❌ No .env.production file and ALB stack not found${NC}"
        echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
        echo "     1. Deploy ALB stack first:"
        echo "        cd ../rfp-infrastructure && ./scripts/deploy-alb.sh"
        echo "     2. Or manually create .env.production with API endpoint:"
        echo "        VITE_API_BASE_URL=http://your-alb-url/api"
        exit 1
    fi
fi

# Install dependencies
echo ""
echo -e "${YELLOW}[3/6] Installing dependencies...${NC}"
if npm install; then
    echo -e "${GREEN}  ✅ Dependencies installed${NC}"
else
    echo -e "${RED}  ❌ npm install failed${NC}"
    echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
    echo "     1. Check Node.js version: node --version (need 18+)"
    echo "     2. Clear npm cache: npm cache clean --force"
    echo "     3. Delete node_modules and package-lock.json, then retry"
    exit 1
fi

# Build the project
echo ""
echo -e "${YELLOW}[4/6] Building React application...${NC}"
if npm run build; then
    echo -e "${GREEN}  ✅ Build completed${NC}"
    # Show build output size
    BUILD_SIZE=$(du -sh dist 2>/dev/null | cut -f1)
    echo -e "${BLUE}  📦 Build size: $BUILD_SIZE${NC}"
else
    echo -e "${RED}  ❌ Build failed${NC}"
    echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
    echo "     1. Check .env.production exists and has valid API endpoint"
    echo "     2. Review build errors above for missing dependencies"
    echo "     3. Ensure Vite config is correct"
    exit 1
fi

# Deploy to S3
echo ""
echo -e "${YELLOW}[5/6] Deploying to S3...${NC}"
FILE_COUNT=$(find dist -type f | wc -l | xargs)
echo -e "${BLUE}  📤 Uploading $FILE_COUNT files to s3://$BUCKET_NAME${NC}"

if aws s3 sync dist/ "s3://$BUCKET_NAME" --delete --region $REGION; then
    echo -e "${GREEN}  ✅ Deployment completed${NC}"
else
    echo -e "${RED}  ❌ S3 sync failed${NC}"
    echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
    echo "     1. Check AWS credentials: aws sts get-caller-identity"
    echo "     2. Verify bucket permissions: aws s3api get-bucket-policy --bucket $BUCKET_NAME"
    echo "     3. Check bucket exists in correct region: aws s3api get-bucket-location --bucket $BUCKET_NAME"
    exit 1
fi

# Invalidate CloudFront cache if distribution exists
echo ""
echo -e "${YELLOW}[6/6] Checking for CloudFront distribution...${NC}"

# Try to get CloudFront ID from CloudFront stack first (manual deployment)
CLOUDFRONT_STACK_NAME="rfp-${ENVIRONMENT}-cloudfront"
CLOUDFRONT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$CLOUDFRONT_STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
    --output text 2>/dev/null || echo "")

# Fall back to master stack if not found
if [ -z "$CLOUDFRONT_ID" ] || [ "$CLOUDFRONT_ID" == "None" ]; then
    CLOUDFRONT_ID=$(aws cloudformation describe-stacks \
        --stack-name "rfp-${ENVIRONMENT}-master" \
        --region "$REGION" \
        --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
        --output text 2>/dev/null || echo "")
fi

if [ -n "$CLOUDFRONT_ID" ] && [ "$CLOUDFRONT_ID" != "None" ]; then
    echo -e "${BLUE}  🔄 Invalidating CloudFront cache for distribution: $CLOUDFRONT_ID${NC}"
    INVALIDATION_ID=$(aws cloudfront create-invalidation \
        --distribution-id "$CLOUDFRONT_ID" \
        --paths "/*" \
        --query 'Invalidation.Id' \
        --output text 2>/dev/null || echo "")
    
    if [ -n "$INVALIDATION_ID" ]; then
        echo -e "${GREEN}  ✅ CloudFront invalidation created: $INVALIDATION_ID${NC}"
        CLOUDFRONT_URL="https://$(aws cloudfront get-distribution --id "$CLOUDFRONT_ID" --query 'Distribution.DomainName' --output text 2>/dev/null)"
        echo -e "${GREEN}  🌐 CloudFront URL: $CLOUDFRONT_URL${NC}"
    else
        echo -e "${RED}  ❌ CloudFront invalidation failed${NC}"
        echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
        echo "     1. Verify CloudFront distribution exists:"
        echo "        aws cloudfront get-distribution --id $CLOUDFRONT_ID"
        echo "     2. Check permissions for CloudFront invalidation"
        echo "     3. Wait for previous invalidations to complete"
    fi
else
    echo -e "${YELLOW}  ⚠️  No CloudFront distribution found${NC}"
    echo -e "${YELLOW}  ℹ️  Troubleshooting:${NC}"
    echo "     1. Deploy CloudFront stack:"
    echo "        cd ../rfp-infrastructure && ./scripts/deploy-cloudfront-manual.sh"
    echo "     2. Or access files directly from S3:"
    echo "        aws s3 ls s3://$BUCKET_NAME"
fi

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}🎉 DEPLOYMENT SUCCESSFUL!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""

if [ -n "$CLOUDFRONT_URL" ]; then
    echo -e "${BLUE}🌐 CloudFront URL:${NC} $CLOUDFRONT_URL"
    echo -e "${BLUE}⏱️  Cache Invalidation:${NC} $INVALIDATION_ID"
    echo -e "${YELLOW}ℹ️  Changes will be visible after cache invalidation completes (1-3 minutes)${NC}"
else
    echo -e "${BLUE}📦 S3 Location:${NC} s3://$BUCKET_NAME"
    echo -e "${YELLOW}ℹ️  Access via CloudFront distribution (check CloudFormation outputs)${NC}"
fi

if [ -n "$ALB_URL" ]; then
    echo -e "${BLUE}🔗 API Endpoint:${NC} $ALB_URL/api"
fi

echo ""
echo -e "${YELLOW}📋 Post-Deployment Verification:${NC}"
echo "   1. Test CloudFront URL in browser (wait 1-3 minutes for cache)"
echo "   2. Check browser console for API errors (F12 → Console)"
echo "   3. Verify API connectivity:"
echo "      curl $ALB_URL/api/actuator/health"
echo "   4. Monitor CloudFront invalidation status:"
echo "      aws cloudfront get-invalidation --distribution-id $CLOUDFRONT_ID --id $INVALIDATION_ID"
echo ""